#include "maat_mem.h"

ATUM_PORT_T* const ptrB = (ATUM_PORT_T*) B_ADDR;
ATUM_PORT_T* const ptrC = (ATUM_PORT_T*) C_ADDR;
ATUM_PORT_T* const ptrD = (ATUM_PORT_T*) D_ADDR;

ATUM_TIMER_8_T* const ptrTimer0 = (ATUM_TIMER_8_T*) TIMER0_ADDR;
ATUM_TIMER_16_T* const ptrTimer1 = (ATUM_TIMER_16_T*) TIMER1_ADDR;
ATUM_TIMER_8_T* const ptrTimer2 = (ATUM_TIMER_8_T*) TIMER2_ADDR;

ATUM_TIMER_INT_MASK_T* const ptrTIMSK = (ATUM_TIMER_INT_MASK_T*) TIMSK_ADDR;
ATUM_TIMER_INT_FLAG_T* const ptrTFLG = (ATUM_TIMER_INT_FLAG_T*) TIFLG_ADDR;
