#include "maat_mem.h"

MAAT_PORT_T* const ptrB = (MAAT_PORT_T*) B_ADDR;
MAAT_PORT_T* const ptrC = (MAAT_PORT_T*) C_ADDR;
MAAT_PORT_T* const ptrD = (MAAT_PORT_T*) D_ADDR;

MAAT_TIMER_8_T* const ptrTimer0 = (MAAT_TIMER_8_T*) TIMER0_ADDR;
MAAT_TIMER_16_T* const ptrTimer1 = (MAAT_TIMER_16_T*) TIMER1_ADDR;
MAAT_TIMER_8_T* const ptrTimer2 = (MAAT_TIMER_8_T*) TIMER2_ADDR;

MAAT_TIMER_INT_MASK_T* const ptrTIMSK = (MAAT_TIMER_INT_MASK_T*) TIMSK_ADDR;
MAAT_TIMER_INT_FLAG_T* const ptrTFLG = (MAAT_TIMER_INT_FLAG_T*) TIFLG_ADDR;

MAAT_USART_T* const ptrUSART = (MAAT_USART_T*) USART_ADDR;

uint8_t* const ptrPRR = (uint8_t*) PRR_ADDR;
